name = "GravityGE"
uuid = "ea95cd53-c789-4503-b9ba-f4afdb1790f4"
license = "MIT"
authors = ["No√© J Nava <noejnava2@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Registrator = "4418983a-e44d-11e8-3aec-9789530b3b3e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"


[compat]
Documenter = "1.13.0"
Infiltrator = "1.9.2"
NamedArrays = "0.10.4"
PkgTemplates = "0.7.56"
Random = "1.11.0"
Registrator = "1.10.0"
Revise = "3.8.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["Test"]
